# This is a basic workflow to help you get started with Actions

name: ℹ️ Workflow Dispatch

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: "fox"
        description: "Enter your name"
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NAME: ${{ inputs.name == "" && "fox" || inputs.name }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Saying Hello to ${{ inputs.name }}
        run: echo Hello, ${{ inputs.name }}!

